<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>default</LangVersion>
        <Nullable>enable</Nullable>
        <RootNamespace>SekaiToolsCore</RootNamespace>
        <Configurations>Debug;Release</Configurations>
        <Platforms>AnyCPU;x64</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Emgu.CV" Version="4.12.0.5764"/>
        <PackageReference Include="SkiaSharp" Version="2.88.9"/>
        <PackageReference Include="HarfBuzzSharp" Version="7.3.0.3"/>
        <PackageReference Include="SkiaSharp.HarfBuzz" Version="2.88.9"/>
    </ItemGroup>

    <ItemGroup Condition="'$(RuntimeIdentifier)' == '' Or $([System.String]::Copy('$(RuntimeIdentifier)').StartsWith('win-'))">
        <PackageReference Include="Emgu.CV.runtime.mini.windows" Version="4.12.0.5764"/>
    </ItemGroup>
    <ItemGroup Condition="'$(RuntimeIdentifier)' == '' Or $([System.String]::Copy('$(RuntimeIdentifier)').StartsWith('osx-'))">
        <PackageReference Include="Emgu.CV.runtime.mini.macos" Version="4.12.0.5764"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SekaiToolsBase\SekaiToolsBase.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
            <_Parameter1>LineEditSelfTest</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

</Project>
